#!/usr/bin/env node
// package.mjs — the one source of truth for what ships and at what version.
//
//   node scripts/package.mjs            # regenerate MANIFEST + VERSION, build the zip
//   node scripts/package.mjs --no-zip   # just regenerate MANIFEST + VERSION
//
// Why this exists: install.sh and Install-Tars.ps1 used to hardcode the list of
// files to fetch, so every time a skill file was added (e.g. connectors.mjs) the
// curl/PowerShell installers silently shipped an incomplete skill. Now the skill
// folder is the source of truth: this script walks it, writes a MANIFEST the
// installers loop over, stamps a VERSION the installers compare against, and
// builds the upload-ready zip for the cloud surfaces (Cowork / claude.ai) that
// have no publish API. Run it before every release and commit the result.
//
// No dependencies. Uses the system `zip` (present on macOS/Linux) for the bundle.

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, rmSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

function fail(msg) { console.error(`  error: ${msg}`); process.exit(1); }

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILL_DIR = join(ROOT, 'skills', 'chief-of-staff');
const DIST = join(ROOT, 'dist');
const noZip = process.argv.includes('--no-zip');

// Files the installers should NEVER fetch: generated artifacts and per-user state.
const EXCLUDE = new Set(['MANIFEST', 'VERSION', 'onboarding-seed.md', '.DS_Store']);

const version = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version;

// Collect the files to ship from GIT-TRACKED contents only, so a stray local
// artifact (a scratch file, a .tars-index/, anything uncommitted) can never leak
// into the manifest/zip. Fall back to a filesystem walk only outside a git tree.
function trackedFiles() {
  const r = spawnSync('git', ['ls-files', '-z', 'skills/chief-of-staff'], { cwd: ROOT, encoding: 'utf8' });
  if (r.error || r.status !== 0 || !r.stdout) return null;
  return r.stdout.split('\0').filter(Boolean)
    .map((p) => relative('skills/chief-of-staff', p).split('\\').join('/'));
}
function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    if (name.startsWith('.')) continue; // never ship hidden files/dirs (e.g. a stray .tars-index/)
    const abs = join(dir, name);
    if (statSync(abs).isDirectory()) { out.push(...walk(abs)); continue; }
    out.push(relative(SKILL_DIR, abs).split('\\').join('/'));
  }
  return out;
}

const files = (trackedFiles() ?? walk(SKILL_DIR))
  .filter((rel) => !EXCLUDE.has(rel.split('/').pop()))
  .sort();
if (!files.includes('SKILL.md')) {
  console.error('  error: SKILL.md not found in the skill folder — refusing to package');
  process.exit(1);
}

// --- MANIFEST: version line + one relative path per line --------------------
const manifest = [
  '# TARS chief-of-staff manifest — generated by scripts/package.mjs. Do not edit by hand.',
  '# Installers read the version line and fetch every file path listed below.',
  `version ${version}`,
  ...files,
  '',
].join('\n');
writeFileSync(join(SKILL_DIR, 'MANIFEST'), manifest);

// --- VERSION: the skill carries its own version on every surface ------------
// (Installers write this locally too, then compare to the remote MANIFEST.)
writeFileSync(join(SKILL_DIR, 'VERSION'), version + '\n');

console.log(`  ✓ MANIFEST + VERSION written  (v${version}, ${files.length} files)`);
for (const f of files) console.log(`      ${f}`);

// --- the upload-ready zip for cloud surfaces --------------------------------
// Cowork / claude.ai have no publish API — skills are uploaded via the web UI
// (Customize → Skills → + → Upload a skill), which expects the SKILL.md folder
// at the zip root. We zip exactly the manifest files (plus MANIFEST/VERSION) —
// an explicit list, so nothing untracked on disk can leak into the bundle.
if (!noZip) {
  mkdirSync(DIST, { recursive: true });
  const zipPath = join(DIST, 'chief-of-staff.zip');
  rmSync(zipPath, { force: true });
  const entries = [...files, 'MANIFEST', 'VERSION'].map((f) => `chief-of-staff/${f}`);
  const r = spawnSync('zip', ['-q', zipPath, ...entries], { cwd: join(ROOT, 'skills'), stdio: 'inherit' });
  if (r.error || r.status !== 0) {
    fail('could not build dist/chief-of-staff.zip (is `zip` installed?). MANIFEST/VERSION were updated; re-run once zip is available, or pass --no-zip.');
  }
  console.log(`  ✓ upload bundle → dist/chief-of-staff.zip`);
}

console.log('');
console.log('  Publish:');
console.log('    • Local (Claude Code):  install.sh / Install-Tars.ps1 / npx now ship v' + version);
console.log('    • Cloud (Cowork, claude.ai):  Customize → Skills → + → Upload a skill →');
console.log('      pick dist/chief-of-staff.zip. Uploads do not auto-update — re-upload to refresh.');
console.log('    See PUBLISHING.md for the full model.');
console.log('');
